config/routes.rb
Rails.application.routes.draw do
  root "welcome#home"
  get 'welcome/about'
  get 'welcome/contact'
  
  get '/signup', to: "registrations#new"
  post '/signup', to: "registrations#create"

  get 'login', to: "sessions#new"
  post '/login', to: "sessions#create" 
  delete '/logout', to: "sessions#destroy"

  get 'users/:id', to: "users#show", as: "profile"

  resources :chatrooms, param: :slug
  resources :messages
  
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  helper_method :current_user, :logged_in?


  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end


  protected

  def authenticate_user!
    redirect_to root_path unless logged_in?
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def index
    @chatroom = Chatroom.new
    @chatrooms = Chatroom.all
  end

  def new
   
    @chatroom = Chatroom.new
  end

  def edit
    @chatroom = Chatroom.find_by(slug: params[:slug])
  end

  def create
    @chatroom = Chatroom.new(chatroom_params)
    if @chatroom.save
      respond_to do |format|
        format.html { redirect_to @chatroom }
        format.js
      end
    else
      respond_to do |format|
        flash[:notice] = {error: ["a chatroom with this topic already exists"]}
        format.html { redirect_to new_chatroom_path }
        format.js { render template: 'chatrooms/chatroom_error.js.erb'} 
      end
    end
  end

  def update
    chatroom = Chatroom.find_by(slug: params[:slug])
    chatroom.update(chatroom_params)
    redirect_to chatroom
  end

  def show
    @chatroom = Chatroom.find_by(slug: params[:slug])
    @message = Message.new
  end

  private

    def chatroom_params
      params.require(:chatroom).permit(:topic)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  skip_before_action :authenticate_user!
  layout 'home', only:[:home]

  def home
   
  end
end

app/views/chatrooms/index.html.erb
<!-- Main -->
<section id="main" class="container">
  <header>
  <h2><b>ChatRoom Platform</b></h2>
    <h2>Welcome to Unipipe ChatRoom platform</h2>
    <p>Select the field to discuss.</p>
    <h2>Select, Explore & Discuss</h2>
  </header>

    <section class="box special features">
    <div class="features-row">
      <section id="medical">
        <span class="icon major fa-bolt accent2"></span>
        <h3><%= link_to "Medical Field", Chatroom.first %></h3>
        <p>Medicine is the science and practice of the diagnosis, treatment, and prevention of disease. Medicine encompasses a variety of health care practices evolved.</p>
      </section>
      <section id="engineering">
        <span class="icon major fa-area-chart accent3"></span>
        <h3><%= link_to "Engineering Field", Chatroom.second %></h3>
        <p>Engineering is the application of mathematics, as well as scientific, economic, social, and practical knowledge to invent, innovate.</p>
      </section>
    </div>
    <div class="features-row">
      <section id="accounting">
        <span class="icon major fa-cloud accent4"></span>
        <h3><%= link_to "Accounting Field", Chatroom.third %></h3>
        <p>Accounting or accountancy is the measurement, processing, and communication of financial information about economic entities such as businesses and corporations.</p>
      </section>
      <section  id="computing_IT">
        <span class="icon major fa-lock accent5"></span>
        <h3><%= link_to "Computing & IT", Chatroom.fourth %></h3> 
        <p>Computer science is the study of the theory, experimentation, and engineering that form the basis for the design and use of computers..</p>
      </section>
    </div>
  </section>

app/views/chatrooms/show.html.erb
<div style="padding-top: 40px;">
  <h1><%= @chatroom.topic %></h1>

<div class="panel panel-default">
  <% if @chatroom.messages.any? %>
    <div class="panel-body" id="messages">
      <%= render partial: 'messages/message', collection: @chatroom.messages%>
    </div>
  <%else%>
    <div class="panel-body hidden" id="messages">
    </div>
  <%end%>
</div>


  <%= render partial: 'messages/message_form', locals: {message: @message, chatroom: @chatroom}%>
</div>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer id="footer">
	<ul class="icons">
		<li><a href="https://plus.google.com/+MikeTanuicomputerguy" class="icon fa fa-google-plus" style="color:red !important;"><span class="label">Googleplus</span></a></li>
		<li><a href="https://twitter.com/KipMyk" class="icon fa-twitter" style="color:#55acee !important;"><span class="label">Twitter</span></a></li>
		<li><a href="https://github.com/mykkip" class="icon fa-github" style="color:#000000 !important;"><span class="label">Github</span></a></li>
		<li><a href="https://ke.linkedin.com/in/kipruto" class="icon fa fa-linkedin" style="color:#007bb5 !important;"><span class="label">Github</span></a></li>
		<li><a href="https://www.youtube.com/channel/UCJOp9o4Q1jTERVKgieGtlvA/featured" class="icon fa fa-youtube" style="color:red !important;"><span class="label">Youtube</span></a></li>
	</ul>
	<ul class="copyright">
        <li>&copy; Unipipe 2018. All rights reserved.</li><li>Design By : <a href="#">VICTOR TURUTHI</a></li>
	</ul>
	<br>
	<ul>
	    <li>
	    	<span>Awesome Programming Project.</span>
	    </li>
	</ul>
</footer>

app/views/layouts/_navbar.html.erb
<div id="page-wrapper">
<!-- Header -->
<header id="header">
  <h1><%= link_to "Unipipe", root_path %></h1>
  <nav id="nav">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li>
        <%= link_to "Chatrooms", chatrooms_path %>
      </li>
      <li>
        <%= link_to "Contact Us", welcome_contact_path, :class => 'icon' %>
      </li>
      <% if current_user %>
      <li><%= link_to "Log out", logout_path, method: "delete" %></li>
      <% else %>
      <li><%= link_to "Sign Up", signup_path, :class => 'button' %>  | </li>
      <li><%= link_to "Log in", login_path, :class => 'button' %></li>
      <% end %>
    </ul>
  </nav>
</header>
</div>

app/views/layouts/_navbar_links.html.erb
<ul class="nav navbar-nav">
  <li>
    <li><%= link_to "Chatrooms", chatrooms_path %></li>
  </li> 
</ul>

<ul class="nav navbar-nav navbar-right">
  <li><%= link_to "Contact Us", welcome_contact_path %></li>
  <% if current_user %>
    <li>
      <%= link_to "Log Out", logout_path, method: "delete" %>
    </li>
  <% else %>
    <li><%= link_to "Sign Up", signup_path %></li>
    <li><%= link_to "Log In", login_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Unipipe</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="author" content="Victor Turuthi" />
    <%= stylesheet_link_tag    'application', 'main', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'main', 'skel.min','util', 'data-turbolinks-track' => 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-fork-ribbon-css/0.2.0/gh-fork-ribbon.min.css" /> -->
  </head>

  <body class="">
   <!-- <a class="github-fork-ribbon right-bottom fixed" href="https://github.com/turuthivic/unipipe" title="check me out on github">Fork me on GitHub</a> -->
  <%= render partial: 'layouts/navbar' %>

  <div class="container">
    <%= yield %>
  </div>
  <%= render partial: 'layouts/footer' %>
  </body>
</html>

app/views/layouts/chatroom.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= Chatroom.name %></title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', 'main', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-fork-ribbon-css/0.2.0/gh-fork-ribbon.min.css" /> -->
  </head>

  <body>
   <!-- <a class="github-fork-ribbon right-bottom fixed" href="https://github.com/turuthivic/unipipe" title="check me out on github">Fork me on GitHub</a> -->

  <div class="container">
    <%= yield %>
  </div>
  <%= render partial: 'layouts/footer' %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Unipipe</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', 'main', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application','main', 'skel.min','util', 'data-turbolinks-track' => 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-fork-ribbon-css/0.2.0/gh-fork-ribbon.min.css" /> -->
  </head>

  <body class="landing">
   <!-- <a class="github-fork-ribbon right-bottom fixed" href="https://github.com/turuthivic/unipipe" title="check me out on github">Fork me on GitHub</a> -->
  <%= render partial: 'layouts/navbar' %>
    <%= yield %>
  <%= render partial: 'layouts/footer' %>
  </body>
</html>

app/views/messages/_message_form.html.erb
<%=form_for message, remote: true, authenticity_token: true do |f|%>
  <%= f.label :your_message%>:
  <%= f.text_area :content, class: "form-control", data: {textarea: "message"}%><br />

  <%= f.hidden_field :chatroom_id, value: chatroom.id %>
  <%= f.submit "send", :class => "btn btn-primary", style: "display: none", data: {send: "message"}%>
<%end%>

app/views/welcome/about.html.erb
<div class="row col-md-8 col-md-offset-2" id="chatroom-title">
  <h1>Chatrooms</h1>
</div>

<div class="row col-md-8 col-md-offset-2" id="chatrooms">
  <%= render partial: 'chatroom_form', locals: {chatroom: @chatroom} %>
  <div id="chatroom-errors">
    
  </div>
    <ul id="chatroom-index"> 
  <% if @chatrooms.any? %>
      <%= render @chatrooms%>
  <%else %>
    </ul>
    <p>Be the first one to make a chatroom!</p>
  <% end %>
</div>

app/views/welcome/contact.html.erb
<!-- Main -->
<section id="main" class="container 75%">
	<header>
		<h2>Contact Me</h2>
		<p>Tell us what you think about our little operation.</p>
	</header>
	<div class="box">
		<form method="post" action="#">
			<div class="row uniform 50%">
				<div class="6u 12u(mobilep)">
					<input type="text" name="name" id="name" value="" placeholder="Name" />
				</div>
				<div class="6u 12u(mobilep)">
					<input type="email" name="email" id="email" value="" placeholder="Email" />
				</div>
			</div>
			<div class="row uniform 50%">
				<div class="12u">
					<input type="text" name="subject" id="subject" value="" placeholder="Subject" />
				</div>
			</div>
			<div class="row uniform 50%">
				<div class="12u">
					<textarea name="message" id="message" placeholder="Enter your message" rows="6"></textarea>
				</div>
			</div>
			<div class="row uniform">
				<div class="12u">
					<ul class="actions align-center">
						<li><input type="submit" value="Send Message" /></li>
					</ul>
				</div>
			</div>
		</form>
	</div>
</section>

app/views/welcome/home.html.erb
<!-- Main -->
<!-- Banner -->
<section id="banner">
  <h2>Unipipe</h2>
  <p>This is an online university pocket platform.</p>
  <p>Here You can discuss any academic related field you are Interested in.</p>
  <ul class="actions">
 	<% if current_user %>
 	<li><%= link_to "Chatrooms", chatrooms_path, :class => "button" %></li>
 	<% else %>
    <li><%= link_to "Sign Up", signup_path, :class => "button special" %></li>
    <li><%= link_to "Learn More", chatrooms_path, :class => "button" %></li>
    <% end %>
  </ul>
</section>

<section id="main" class="container">
	<section class="box special">
		<header class="major">
			<h2>Introducing the online university discussion platform
			<br />
			for you</h2>
			<p>This platform will enable you to achieve and share your knowledge in anyfield<br />
			& most importantly is that the platform is free to use.</p>
		</header>
		<span class="image featured"><%= image_tag("pic01.jpg") %></span>
	</section>

	<section class="box special features">
		<div class="features-row">
			<section id="mdical">
				<span class="icon major fa-bolt accent2"></span>
				<% if current_user %>
				<h3><%= link_to "Medical Field", Chatroom.first %></h3>
				<% else %>
				<h3><%= link_to "Medical Field", signup_path %></h3>
				<% end %>
				<p>Medicine is the science and practice of the diagnosis, treatment, and prevention of disease. Medicine encompasses a variety of health care practices evolved.
				<br>
				<br>
					<li><%= link_to "Learn more", chatrooms_path, :class => 'button alt' %></li>
				</p>
			</section>
			<section id="engineering">
				<span class="icon major fa-area-chart accent3"></span>
				<% if current_user %>
				<h3><%= link_to "Engineering Field", Chatroom.second %></h3>
				<% else %>
				<h3><%= link_to "Engineering Field", signup_path %></h3>
				<% end %>
				<p>Engineering is the application of mathematics, as well as scientific, economic, social, and practical knowledge to invent, innovate.
				<br>
				<br>
					<li><%= link_to "Learn more", chatrooms_path, :class => 'button alt' %></li>
				</p>
			</section>
		</div>
		<div class="features-row">
			<section id="computing">
				<span class="icon major fa-cloud accent4"></span>
				<% if current_user %>
				<h3><%= link_to "Accounting", Chatroom.third %></h3>
				<% else %>
				<h3><%= link_to "Accounting", signup_path %></h3>
				<% end %>
				<p>Accounting or accountancy is the measurement, processing, and communication of financial information about economic entities such as businesses and corporations
				<br>
				<br>
					<li><%= link_to "Learn more", chatrooms_path, :class => 'button alt' %></li>
				</p>
			</section>
			<section  id="accounting">
				<span class="icon major fa-lock accent5"></span>
				<% if current_user %>
				<h3><%= link_to "Computing & IT", Chatroom.fourth %></h3>
				<% else %>
				<h3><%= link_to "Computing & IT", signup_path %></h3>
				<% end %>
				<p>
				Computer science is the study of the theory, experimentation, and engineering that form the basis for the design and use of computers.
				<br>
				<br>
					<li><%= link_to "Learn more", chatrooms_path, :class => 'button alt' %></li>
				</p>
			</section>
		</div>
	</section>

	<div class="row">
		<div class="6u 12u(narrower)">

			<section class="box special">
				<span class="image featured"><%= image_tag("pic02.jpg") %></span>
				<h3>Unipipe - Chatplatform</h3>
				<p>This is the best online university discussion forumn open to every anybody.</p>
				<ul class="actions">
					<li><%= link_to "Learn more", chatrooms_path, :class => 'button alt' %></li>
				</ul>
			</section>

		</div>
		<div class="6u 12u(narrower)">

			<section class="box special">
				<span class="image featured"><%= image_tag("pic03.jpg") %></span>
				<h3>Unipipe - Archive patform</h3>
				<p>Here you can achieve your research but rstricting the people who can assest them.</p>
				<ul class="actions">
					<li><%= link_to "Learn more", chatrooms_path, :class => 'button alt' %></li>
				</ul>
			</section>

		</div>
	</div>

</section>

<!-- CTA -->
<section id="cta">

	<h2>Sign up for free to get started</h2>
	<h3><b>Play,  Explore  &  Learn</b></h3>

	<form>
		<div class="row uniform 50%">
			<div class="8u 12u(mobilep)">
				<input type="email" name="email" id="email" placeholder="Email Address" />
			</div>
			<div class="4u 12u(mobilep)">
				<input type="submit" value="Sign Up" class="fit" />
			</div>
		</div>
	</form>

</section>